### ISSUE TITLE
May I ask you a question？It has bothered me for a long time.

### ISSUE THREAD

**Issue by Kaido0** [joseabernal/iSeg2017-nic_vicorob#3]
May I ask you a question？It has bothered me for a long time.
In  brain tissue segmentation,always use sliding window method to traverse the entire MR image, making the entire image into many small pieces like (27*27*27),for training and testing.
But I refer to voc2012 and they generally use the entire image directly for segmentation without using sliding window. Why does the brain image need do this? Can small patches consider the global features?
By the way,are you divided brain into three categories:wm,gm,csf,not consider background in train dataset and test datasets also in the model you have trained？
Sorry for my poor English~

**Comment by joseabernal** [comment]
1) The larger the patch dimension, the more resources you need. I'd say it is primarily because of the computational constraint that we do not process a whole image at once. Another advantage it gives you is the possibility of using a trained network on different data collections -- recall that all the volumes may not be acquired with the same resolution. Also, note that in here we are working with 3D volumes and not 2D ones as in VOC2012 (correct me if mistaken). 
You could process an MR volume slice-wise -- using a 2D u-shaped network, for instance --, but usually, 3D architectures perform better than 2D as seen in https://arxiv.org/abs/1801.06457. I have not seen an approach handling the whole 3D vol at once.
2) Tissue segmentation in brain MRI consists in segmenting the input into CSF, GM and WM. In this case, the iSeg-2017 datasets are already skull stripped (hence, background intensity equal to zero), meaning there is no need to consider the background class. Nevertheless, in other datasets, you may want to consider it.
3) Do not worry, I'm not native either :P

**Comment by Kaido0** [comment]
@joseabernal 
Thank you for your patient explanation^_^
I don't understand the another advantage(data collections),you mean we can use data augment?

**Comment by joseabernal** [comment]
What I mean is that images from different datasets may have a different resolution (some 256x256x256, some other 256x192x128, etc.). If you were able to train a network with patches of size 256x256x256, you could not use it to work on other datasets.

**Comment by Kaido0** [comment]
Oh~I got it
Thank you very much.
Have a nice day~

**Comment by Kaido0** [comment]
@joseabernal 
Oh ! I got it
Thank you very much.Have a nice day
